### PR TITLE
Adding binary for printing an AST to the console

### PR DESCRIPTION
**Pull request by mrjoelkemp**

### CODE REVIEW

**Comment by tonyganch** [comment]
What command should I use to run it locally without `npm i -g`?
`node ./bin/gonzales.js path/to/file`?

**Comment by tonyganch** [comment]
Oh, I've managed to run it.

Thank you!
Are you sure you want `.toString()` method instead of `gonzales.astToTree()`?

Example of `ast.toString()`:

``` js
[ 'stylesheet',
  [ 'ruleset', [ 'selector', [Object] ], [ 'block' ] ],
  [ 's', '\n' ],
  [ 'ruleset', [ 'selector', [Object] ], [ 'block' ] ],
  [ 's', '\n' ] ]
```

Example of `gonzales.astToTree(ast)`:

``` js
['stylesheet',
  ['ruleset',
    ['selector',
      ['simpleselector',
        ['ident', 'a'],
        ['s', ' ']]],
    ['block']],
  ['s', '
'],
  ['ruleset',
    ['selector',
      ['simpleselector',
        ['class',
          ['ident', 'b']],
        ['pseudoc',
          ['ident', 'hover']],
        ['s', ' ']]],
    ['block']],
  ['s', '
']]
```

**Comment by mrjoelkemp** [comment]
Great tip on using astToTree for the prettier output. I also added the details on the shell command usage in the Readme.

**Comment by tonyganch** [comment]
@mrjoelkemp, merged into `dev` branch. Thank you!

**Pull request closed without merging**
