### PR TITLE
Documentation "Sample code" fix

### PR DESCRIPTION
**Pull request by ololobus**
Usage documentation mismatch fixed

### CODE REVIEW

**Comment by ololobus** [comment]
But I think, it would be great to have possibility to pass only AST object into astToCSS function (instead of `{ ast: ast }`)

It can be done by adding an if statement 

``` js
tree = (typeof options === 'string' || options[0] && options[0] === 'stylesheet') ? options : options.ast;
```

to file https://github.com/tonyganch/gonzales-pe/blob/master/src/ast-to-css.js

I can create a pull-request :)

**Comment by tonyganch** [comment]
Ha-ha, I've just created #13 with opposite point of view :)

That line causes a bug in fact: `tree` must be an array, not a string or an object.
Why would you like to pass only AST, without syntax name?

**Comment by ololobus** [comment]
Heh =)
Because syntax name is "css" by default, `astToCSS(ast)` is shorter than `astToCSS({ ast: ast })` and it makes possible to write code in this way

``` js
newCSS = parser.astToCSS(do_something_with(parser.cssToAST(css)));
```

OK, tree is array, it was example if, I've just fixed it

**Comment by tonyganch** [comment]
Ok.
So I'm closing this PR in favour of your future "if" PR? :)

Out of curiosity: why do you need Gonzales?

**Comment by tonyganch** [comment]
If you're going to open another PR, will you be so nice to open it for `dev` branch, please?

**Comment by ololobus** [comment]
OK

**Pull request closed without merging**
