### PR TITLE
fixes #124. trailing parent selectors in mixins

### LINKED ISSUE #124: Parent Selector for Mixins Broken
Using 3.2.1. The following block of LESS is valid, but gonzales-pe throws an error for the first line:

```
.standard-button-primary () {
  &[type=button],
  input[type=button]&,
  &[type=reset],
  input[type=reset]&,
  &[type=submit],
  input[type=submit]& {
    background-color: #000;
    .cssgradients & {

      &:not(:disabled):not(.disabled) {
        &:hover {
          background-color: #000;
          background-image: none; // override gradient
        }
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by shellscape**
This adds support for a "new" combinator of `TokenTypes.Ampersand` to `checkCombinator2` in order to support trailing parent selectors on selectors within mixins.

### CODE REVIEW

**Comment by tonyganch** [comment]
The thing is parent selector is a selector, not a combinator.
So what we can do here. We can go to `checkCompoundSelector1` and `checkCompoundSelector2` and  inside the while-loop add `checkParentSelectorWithExtension(i)`:
https://github.com/gilt/gonzales-pe/blob/trailing-parent-selectors/src/less/parse.js#L3613
And inside `getCompoundSelector...` we should add `getParent...`:
https://github.com/gilt/gonzales-pe/blob/trailing-parent-selectors/src/less/parse.js#L3635

**Comment by shellscape** [comment]
Yeah none of that makes any real sense to me. Spent about 8 hours combined trying to figure out how to work with the repo, and how those parts of the parser work, in order to get these tests passing. I'm not really keen on jumping back in and learning how an entirely new segment of it works just to resolve the issue in a completely different way. Honestly, that's pretty disheartening.

This fixes a pretty critical oversight and **breaking bug** in the 3.x versions that worked fine with 3.0.0.-31. At the very least, with all tests passing, it should be merged and "corrected" in a patch version.

**Comment by tonyganch** [comment]
Can I ask you why you use this parser at all?

**Comment by shellscape** [comment]
Certainly! The lesshint project uses it extensively, and I actively contribute to that project. Regardless of what I think personally of gonzales-pe's structure before publishing, the end result works very well for lesshint's needs as I understand it.

In order to take advantages of improvements you've made, they've depended upon 3.x. Unfortunately 3.x now throws false-positive parsing errors for nearly 100 of our less files. Action was necessary to try and speed up the timing of those fixes.

**Comment by kokarn** [comment]
Any progress on this PR?

**Comment by tonyganch** [comment]
@shellscape 

> This fixes a pretty critical oversight and breaking bug

Well, it does not. The only thing this pr does is stop parser from throwing errors by adding another bug.

> At the very least, with all tests passing, it should be merged and “corrected” in a patch version.

Apparently, “all tests passing” can’t be an argument because they all pass even now without this pr and unfixed issue. What you propose here is that I merge the pull request with a bug and fix it myself later. Can you see how absurd it sounds?

Ampersand is a parent selector, so parsing it as a combinator is an error.

**Comment by shellscape** [comment]
Unfortunately I don't have any more time to give for PRs on the project. Our fork is no longer throwing exceptions and is allowing us to move forward. A bug that doesn't throw exceptions is better than a bug that throws an exception and halts execution, imho. Your project, so it's completely your call. I won't take offense to my PRs being closed as invalid, but I don't think having your project throw exceptions and halt execution on valid LESS syntax is better.

**Comment by shellscape** [comment]
abandoning, moved on to use PostCSS and https://github.com/webschik/postcss-less.

**Pull request closed without merging**
