### PR TITLE
Update minimist version

### PR DESCRIPTION
**Pull request by guoyunhe**
See https://github.com/advisories/GHSA-7fhm-mqm4-2wp7

### CODE REVIEW

**Comment by watson** [comment]
This should really be `^1.2.5` as a few other security issues were fixed in later versions

**Comment by guoyunhe** [comment]
Updated to ^1.2.5

**Comment by theogravity** [comment]
@tonyganch could you look at this PR?

**Comment by shaundr** [comment]
What are we waiting on?

**Comment by jamestharpe** [comment]
Looks like some updates may need to be made to the CI process as well: https://travis-ci.org/github/tonyganch/gonzales-pe/jobs/663227249?utm_medium=notification&utm_source=github_status

**Pull request merged**
