### PR TITLE
Custom properties with interpolation

### PR DESCRIPTION
**Pull request by jdalton**
This WIP PR addresses #290 and adds support for custom properties with interpolation to sass/scss.

### CODE REVIEW

**Comment by jdalton** [comment]
Ok imma merge this. I've ran `gonzales-pe` against [csscomb.js](https://github.com/csscomb/csscomb.js) without additional test fails. :tada:

**Comment by nelson6e65** [comment]
Awesome! When will be this released? :smiley:

**Comment by TheJaredWilcurt** [comment]
Never?

**Comment by webartov** [comment]
> Never?

I suppose the fix https://github.com/tonyganch/gonzales-pe/issues/290 was released for the issue with `--someVar: #fff;` As it works fine now.
But fix for the issue with `$--someVar: #fff;` was never released =( https://github.com/tonyganch/gonzales-pe/issues/290#issuecomment-593302895

**Pull request merged**
